import ClientProvider from './component/ClientProvider'
import './globals.css'
export const metadata = {
  title: 'PMFC Furniture',
  description: 'Generated by Next.js',
}
import dynamic from 'next/dynamic'



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ClientProvider>
          <main>{children}</main>
        </ClientProvider>
      </body>
    </html>
  )
}
