import type { Metadata } from 'next'
import '../globals.css'
import ClientLayout from './components/ClientLayout'

export const metadata: Metadata = {
  title: 'PMFC Furniture',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClientLayout>
      <main>{children}</main>
    </ClientLayout>
  )
}
