import type { Metadata } from "next";
import { Montserrat } from 'next/font/google'
import "../globals.css";
import ClientLayout from "./components/ClientLayout";

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <ClientLayout>
          <main>{children}</main>
        </ClientLayout>
  )
}
